### ISSUE TITLE
[FEATURE] Append to authorized keys

### ISSUE THREAD

**Issue by PFigs** [wirepas/wm-config#10]
The wm-config acts on the authorized keys by replacing.

**Describe the solution you'd like**
Either append to existing or allow a flag to control the manipulation behaviour

**Comment by JanneSiren** [comment]
Authorized key handling should be reconsidered in wider aspect:
1. Configuring of x86 and arm systems should not differ the way it currently does. Currently there are many aspects that are done only in Raspberry Pi. Many of those should not be architecture specific, instead those should be use case specific. By default x86 and arm installations should look alike. In case "EVK use case" requires something else than default (that can be used in both x86 and arm), "EVK use case" should have own "EVK defaults".
2. In case administrators have entered their keys to authorized_keys before setting up wm-config, by default wm-config setup script should not remove those. Should not matter is it arm or x86. In case "EVK use case" requires special key handling, it should be done under flag set in "EVK defaults".
3. Currently default.env contains a key that someone may or may not have public key. Nobody else than the creator of that public key can really be sure that private key for that does not exist. The idea clearly is that the key is customized, but problem is that customization is not enforced. It should be prevented to install any "default" public key, as if it would be installed, it is security issue.

**Comment by PFigs** [comment]
1. - See #11 
2. - The concern was to avoid a pre-shared key to be inadvertently known by different organizations. I do agree the overwrite can lead to unexpected situations and appending seems the way to go.
3. - Agree, it should be empty. The default appeared to help with what it should contain, but I think that can be better address with finer examples like those foreseen in #8 .
